server:
  port: 8080
  
spring:
  application:
    name: shabao-blog
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.91.220.42:3306/db_mblog?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: master
    password: 19911105man
    
  #jpa配置
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      hibernate.cache.use_second_level_cache: false
      hibernate.search.default.directory_provider: filesystem
      hibernate.search.default.indexBase: ./indexes
    open-in-view: true
    
  #freemarker配置
  freemarker:
    request-context-attribute: request
    settings:
      number_format: 0.##
    
  cache:
#    cache-names: sysConfig
#    time-to-live: 10000  	
  redis:
    database: 2
    port: 6379
    host: 47.91.220.42
    password: 19911105man
    pool:
      max-active: 20
  
#mybatis
mybatis:
  #实体类包名，设置后可以用类名代替全路径名称
  type-aliases-package: com.xiaoshabao.blog.entity
  #设置mapper存放位置
  mapper-locations: classpath:mapper/**.xml
  #开启驼峰命名规范
  configuration:
    mapUnderscoreToCamelCase: true

logging:
  level:
    root: INFO
    com.xiaoshabao.blog.mapper: DEBUG
#  path: C:/logs/log.log