server:
  ssl:
    key-store: classpath:full_chain.pem
    key-store-password: MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgHctEMcJhS7OAwldTmsJevnNcpvhN0mYwDj666+Ph4WOgCgYIKoZIzj0DAQehRANCAASLcU0rXujLQ8CKj41bRlI/+juDe7m/g9Iik1bSntHB1gBoOxC+uTQplUOrZUYZt+RILsf/0UpoA4rhagWr/t4k
    keyStoreType: ECC
    
spring:
  profiles: prd
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.91.220.42:3306/shabao_blog?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: master
    password: 19911105man
  jpa:
    properties:
      hibernate.search.default.indexBase: /app/data/indexs
  redis:
    database: 3
    port: 6379
    host: 47.91.220.42
    password: 19911105man
    pool:
      max-active: 20

logging:
  level:
    root: INFO
    com.xiaoshabao.blog.mapper: DEBUG
  path: /app/data/logs
